//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graduation_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int ID { get; set; }

        public int clinicID { get; set; }
        public int doctorID { get; set; }
        public int personID { get; set; }
        [Display(Name = "«·Õ«·…")]
        public Nullable<bool> active { get; set; }
        [Display(Name = "«·„Ê⁄œ")]
        public System.DateTime date { get; set; }
        [Display(Name = "„·«ÕŸ…")]
        public string note { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Person Person { get; set; }
    }
}
